<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <UserSecretsId>dotnet-HarborAdmin.TaskWorker</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Quartz.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Data\HarborAdmin.BuildingBlocks.Data.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.EventBus\HarborAdmin.BuildingBlocks.EventBus.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Mapping\HarborAdmin.BuildingBlocks.Mapping.csproj" />
        <ProjectReference Include="..\..\client\HarborAdmin.Client.ConfigCenter\HarborAdmin.Client.ConfigCenter.csproj" />
        <ProjectReference Include="..\..\modules\HarborAdmin.Modules.TaskOrchestration\HarborAdmin.Modules.TaskOrchestration.csproj" />
    </ItemGroup>

</Project>
