<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Abstractions\HarborAdmin.BuildingBlocks.Abstractions.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Caching\HarborAdmin.BuildingBlocks.Caching.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Data\HarborAdmin.BuildingBlocks.Data.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Mapping\HarborAdmin.BuildingBlocks.Mapping.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Application\Captcha\Assets\captcha\**\*" />
      <Content Include="Application\Captcha\Assets\captcha\**\*">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="SkiaSharp" />
      <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    </ItemGroup>

</Project>
