<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FreeSql" />
        <PackageReference Include="FreeSql.Cloud" />
        <PackageReference Include="FreeSql.Repository" />
        <PackageReference Include="FreeSql.Provider.MySql" />
        <PackageReference Include="FreeSql.Provider.PostgreSQL" />
        <PackageReference Include="FreeSql.Provider.Sqlite" />
        <PackageReference Include="FreeSql.Provider.SqlServer" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Yitter.IdGenerator" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HarborAdmin.BuildingBlocks.Abstractions\HarborAdmin.BuildingBlocks.Abstractions.csproj" />
    </ItemGroup>
</Project>
