<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Abstractions\HarborAdmin.BuildingBlocks.Abstractions.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Application\HarborAdmin.BuildingBlocks.Application.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.AspNetCore\HarborAdmin.BuildingBlocks.AspNetCore.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Data\HarborAdmin.BuildingBlocks.Data.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.EventBus\HarborAdmin.BuildingBlocks.EventBus.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Mapping\HarborAdmin.BuildingBlocks.Mapping.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Secrets\HarborAdmin.BuildingBlocks.Secrets.csproj" />
        <ProjectReference Include="..\..\client\HarborAdmin.Client.AI\HarborAdmin.Client.AI.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
