<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <UserSecretsId>dotnet-HarborAdmin.AIWorker</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Data\HarborAdmin.BuildingBlocks.Data.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.EventBus\HarborAdmin.BuildingBlocks.EventBus.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Mapping\HarborAdmin.BuildingBlocks.Mapping.csproj" />
        <ProjectReference Include="..\..\buildingBlocks\HarborAdmin.BuildingBlocks.Secrets\HarborAdmin.BuildingBlocks.Secrets.csproj" />
        <ProjectReference Include="..\..\client\HarborAdmin.Client.ConfigCenter\HarborAdmin.Client.ConfigCenter.csproj" />
        <ProjectReference Include="..\..\client\HarborAdmin.Client.AI\HarborAdmin.Client.AI.csproj" />
        <ProjectReference Include="..\..\modules\HarborAdmin.Modules.AI\HarborAdmin.Modules.AI.csproj" />
        <ProjectReference Include="..\..\modules\HarborAdmin.Modules.Secrets\HarborAdmin.Modules.Secrets.csproj" />
    </ItemGroup>

</Project>
